//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RnD {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CustomResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CustomResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RnD.CustomResources", typeof(CustomResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;authorization_endpoint&quot;: &quot;http://localhost:86/Azure/8ca249c4-1128-4adb-82b7-31c72d015e09/oauth2/v2.0/authorize&quot;,
        ///    &quot;token_endpoint&quot;: &quot;http://localhost:86/Azure/8ca249c4-1128-4adb-82b7-31c72d015e09/oauth2/v2.0/token&quot;,
        ///    &quot;token_endpoint_auth_methods_supported&quot;: [
        ///        &quot;client_secret_post&quot;,
        ///        &quot;private_key_jwt&quot;,
        ///        &quot;client_secret_basic&quot;
        ///    ],
        ///    &quot;jwks_uri&quot;: &quot;http://localhost:86/Azure/8ca249c4-1128-4adb-82b7-31c72d015e09/discovery/v2.0/keys&quot;,
        ///    &quot;response_modes_supported&quot;: [        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string WellKnownConfiguration {
            get {
                return ResourceManager.GetString("WellKnownConfiguration", resourceCulture);
            }
        }
    }
}
